Repository YouHyeok/Tom, pull requests merged in 2023-10, with the labels that each got.

#2 fix #1
  Tom/Tom.xcodeproj/project.pbxproj
  Tom/Tom.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Tom/Tom.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Tom/Tom/Assets.xcassets/AccentColor.colorset/Contents.json
  Tom/Tom/Assets.xcassets/AppIcon.appiconset/Contents.json
  Tom/Tom/Assets.xcassets/Contents.json
  Tom/Tom/ContentView.swift
  Tom/Tom/Preview Content/Preview Assets.xcassets/Contents.json
  Tom/Tom/TomApp.swift
  Tom/TomTests/TomTests.swift
  Tom/TomUITests/TomUITests.swift
  Tom/TomUITests/TomUITestsLaunchTests.swift
Labels: enhancement, development, Projects

#6 fix #5
  YouHyeok/Tom/__init__.py
  YouHyeok/Tom/__pycache__/__init__.cpython-310.pyc
  YouHyeok/Tom/__pycache__/admin.cpython-310.pyc
  YouHyeok/Tom/__pycache__/apps.cpython-310.pyc
  YouHyeok/Tom/__pycache__/models.cpython-310.pyc
  YouHyeok/Tom/__pycache__/urls.cpython-310.pyc
  YouHyeok/Tom/__pycache__/views.cpython-310.pyc
  YouHyeok/Tom/admin.py
  YouHyeok/Tom/apps.py
  YouHyeok/Tom/migrations/__init__.py
  YouHyeok/Tom/migrations/__pycache__/__init__.cpython-310.pyc
  YouHyeok/Tom/models.py
  YouHyeok/Tom/serializers.py
  YouHyeok/Tom/tests.py
  YouHyeok/Tom/urls.py
  YouHyeok/Tom/views.py
  YouHyeok/YouHyeok/__init__.py
  YouHyeok/YouHyeok/__pycache__/__init__.cpython-310.pyc
  YouHyeok/YouHyeok/__pycache__/settings.cpython-310.pyc
  YouHyeok/YouHyeok/__pycache__/urls.cpython-310.pyc
  YouHyeok/YouHyeok/__pycache__/wsgi.cpython-310.pyc
  YouHyeok/YouHyeok/asgi.py
  YouHyeok/YouHyeok/settings.py
  YouHyeok/YouHyeok/urls.py
  YouHyeok/YouHyeok/wsgi.py
  YouHyeok/db.sqlite3
  YouHyeok/manage.py
Labels: enhancement, development, Projects

#7 fix #5
  YouHyeok/Tom/__pycache__/urls.cpython-310.pyc
  YouHyeok/Tom/__pycache__/views.cpython-310.pyc
  YouHyeok/Tom/urls.py
  YouHyeok/Tom/views.py
Labels: enhancement, development, Projects

#9 fix #8
  analysis.ipynb
Labels: enhancement, development, Projects

#13 fix #12
  YouHyeok/Tom/views.py
  YouHyeok/YouHyeok/settings.py
Labels: enhancement, development, Projects

#17 fix #14
  Tom/.DS_Store
  Tom/Pods/Pods.xcodeproj/project.pbxproj
  Tom/Tom.xcodeproj/project.pbxproj
  Tom/Tom.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Tom/Tom/ContentView.swift
  Tom/Tom/Model/LCategories.swift
  Tom/Tom/Networking/Networking.swift
  Tom/Tom/SecondView.swift
Labels: enhancement, development, Projects

#20 fix #19
  YouHyeok/Tom/views.py
Labels: enhancement, development, Projects

#21 Feat #18
  Tom/Tom/Assets.xcassets/.DS_Store
  Tom/Tom/Assets.xcassets/AppIcon.appiconset/Contents.json
  Tom/Tom/Assets.xcassets/AppIcon.appiconset/tomicon3.png
  Tom/Tom/Assets.xcassets/yh.imageset/Contents.json
  Tom/Tom/Assets.xcassets/yh.imageset/new_yh_logo_128.png
  Tom/Tom/Assets.xcassets/yh.imageset/yh21_128.png
  image1.png
  image2.png
Labels: Projects

#23 Feat #22
  Tom/.DS_Store
  Tom/Tom.xcodeproj/project.pbxproj
  Tom/Tom/ContentView.swift
  Tom/Tom/Model/UpResults.swift
  Tom/Tom/Networking/Networking.swift
  Tom/Tom/SecondView.swift
Labels: enhancement, development, Projects

#26 fix #25
  YouHyeok/Tom/migrations/__pycache__/__init__.cpython-311.pyc
  YouHyeok/Tom/views.py
  YouHyeok/YouHyeok/settings.py
Labels: enhancement, development, Projects, Publish, Beta

#27 Beta v1.0.1
  YouHyeok/Tom/migrations/__pycache__/__init__.cpython-311.pyc
  YouHyeok/Tom/views.py
  YouHyeok/YouHyeok/settings.py
Labels: enhancement, development, Projects, Publish, Beta
